all: ticTacToeResult hiddenLoop

.outputFolder:
	mkdir -p out
	
ticTacToeResult: .outputFolder
	clang -std=c++17 -lstdc++ -lm ticTacToeResult.cpp -Wall -Wextra -Werror -o out/ticTacToeResult
	./out/ticTacToeResult

hiddenLoop: .outputFolder
	clang -std=c++17 -lstdc++ -lm hiddenLoop.cpp -Wall -Wextra -Werror -o out/hiddenLoop
	./out/hiddenLoop

hiddenLoopConnectFourTypaShit: .outputFolder
	clang -std=c++17 -lstdc++ -lm hiddenLoopConnectFourTypaShit.cpp -Wall -Wextra -Werror -o out/hiddenLoopConnectFourTypaShit
	./out/hiddenLoopConnectFourTypaShit

connectFourResult: .outputFolder
	clang -std=c++17 -lstdc++ -lm connectFourResult.cpp -Wall -Wextra -Werror -o out/connectFourResult
	./out/connectFourResult

connectFourResult_v2: .outputFolder
	clang -std=c++20 -lstdc++ -lm connectFourResult_v2.cpp -Wall -Wextra -Werror -o out/connectFourResult_v2
	./out/connectFourResult_v2

connectFourResult_absoluteSuperDuperFinalVersionPLEASEIMBEGGING: .outputFolder
	clang -std=c++20 -lstdc++ -lm connectFourResult_absoluteSuperDuperFinalVersionPLEASEIMBEGGING.cpp -Wall -Wextra -Werror -o out/connectFourResult_absoluteSuperDuperFinalVersionPLEASEIMBEGGING
	./out/connectFourResult_absoluteSuperDuperFinalVersionPLEASEIMBEGGING
